### PR TITLE
Spaceplane passenger cabins should require training

### PR DESCRIPTION
**Pull request by nova-ad-astra**
They used to default to 0 training time, which is not the desired behavior. The training times will now instead equal the equivalent capsule from the same tech node with the same reentry rating and bulkhead profile.

### CODE REVIEW

**Comment by ec429** [comment]
Idk, isn't half the point of spaceplanes that passengers can ride in them with less vehicle-specific training?  The passengers don't need to be trained to pilot the thing...

I think they should have much lower proficiency training times than cockpits/capsules, but the same mission training time.

**Comment by nova-ad-astra** [comment]
@ec429 Well in real life, certainly. This could possibly be modeled, but from a gameplay point of view I believe players are more likely to train the entire crew in batch (I certainly do). If you split the training times, you either have to start training at two separate times to sync up the mission training expiry for your pilots/passengers (fiddly) or you'd run the risk of the passengers losing their mission readiness before your pilots, potentially making you start the training process all over again (frustrating).

Keeping it balanced means you have to initiate mission training once, the crew will all be ready to go at the same time and everything just works. You lose out on certain edge cases such as being able to hire and train extra crew after starting your pilot training in case you redecide on your desired crew count, but other than that this seems like the least painful solution.

**Comment by ec429** [comment]
That's why I said the _mission_ training would match the cockpit.  It's only the _proficiency_ training that would be shorter for the cabin.

**Comment by lpgagnon** [comment]
2 things to keep in mind (sort of repeating things from discord)
- There's not really a use case for "passengers" in rp-1; seems like the concept would need to be better-defined before any effort at fine-tuning training times. 'same as capsules' seems like a better, less-abusable default until that point
- For those who do have a "legitimate" use case for passengers, there's plenty of options for getting around training times (e.g. training in the ROEngines Launch Tower), so this change won't actually hard-block anything

**Comment by lpgagnon** [comment]
... never mind https://github.com/KSP-RO/RP-0/commit/4850b31675a56af11cb6639d5c8d1f926bad2d96

**Comment by NathanKell** [comment]
Yeah, I tend to think the best option here is very quick (a week?) or nonexistent proficiency training, and reasonable mission training.

**Comment by DRVeyl** [comment]
Did 1636 actually implement this, and can it be closed?

**Comment by siimav** [comment]
No, it did not

**Pull request closed without merging**
