### PR TITLE
Note the format for putting in dates for simulations

### PR DESCRIPTION
**Pull request by Clayell**
**PLEASE CHECK THAT THIS IS ACTUALLY THE RIGHT FORMAT**

The format for dates varies around the world, so it is important to actually mention the format that this date is supposed to be in instead of just assuming.

### CODE REVIEW

**Comment by siimav** [comment]
I'm not entirely sure this is necessary. Why not just change the date example to values that isn't ambiguous?

**Comment by Clayell** [comment]
> I'm not entirely sure this is necessary. Why not just change the date example to values that isn't ambiguous?

Oh sure, that could also work.
Is it yyyy-mm-dd btw?

**Comment by siimav** [comment]
> Is it yyyy-mm-dd btw?

Of course! Why would anyone order date components in anything other than ascending or descending?

**Comment by Clayell** [comment]
Of course, why would anyone do that. 👀

**Pull request merged**
