### PR TITLE
Fixing descriptions

### PR DESCRIPTION
**Pull request by Clayell**
Typo in 3-satellite constellation

### CODE REVIEW

**Comment by Clayell** [comment]
Add x10 multiplier for the com sat payload for molniya contracts to make up for the fact that about 10x payload can be put into a leo than a molniya orbit

**Comment by siimav** [comment]
Adding different kinds of changes into the same PR is a very bad practice.

**Comment by Clayell** [comment]
Woops, meant to make this into another branch, sorry. Should I revert this and make it into a different pull?

**Comment by siimav** [comment]
Yes

**Pull request merged**
