### PR TITLE
Chinese Leader Update.

### PR DESCRIPTION
**Pull request by Proxima-b**
I noticed an unused leader icon in the file.
Plan to expand upon it.

### CODE REVIEW

**Comment by Capkirk123** [comment]
Is this finished?

**Comment by Proxima-b** [comment]
> Is this finished?

Technically it is, the thing is, there was already an picture of that scientist in the files. 
This PR is only aimed to complete the that specific unused asset, not as a fully complete chinese leader update.

**Comment by Capkirk123** [comment]
Probably a little week, but eh. Ship now, balance later.

**Comment by Proxima-b** [comment]
Tried a little, The leader does lack significant impact, maybe increase the integration rate for another 5%, make him a rush option, considering the Reputation malus ?

**Comment by Proxima-b** [comment]
> Probably a little week, but eh. Ship now, balance later.

Tried a little, The leader does lack significant impact, maybe increase the integration rate for another 5%, make him a rush option, considering the Reputation malus ?

**Pull request merged**
