### PR TITLE
Clarify description of Early Comms Network program

### PR DESCRIPTION
**Pull request by Amselfass**
Since many other programs give the player hints regarding the minimum research required to complete them, I have added a note that Comms TL2 is required for actually having a useful network (even though I think the contract might not enforce it). I have also clarified the unhelpful statement about „fairly high“ orbits.

### CODE REVIEW

**Comment by Blothorn** [comment]
I think this just promotes the misunderstanding that this is supposed to be a stock-style relay constellation for player use, not a commercial network that would not normally have hardware for connecting to other spacecraft.

**Comment by Amselfass** [comment]
I guess you can pencil me in as another victim of this misunderstanding then. :D

**Comment by LuneoLucy** [comment]
I definitely agree on changing the program and even contracts definitions of the early com network I don't really understand what this wants the player to think of it, i'm not sure this is the change it needs but i hope your PR will contribute to the potential change :) 

As for discord reactions, don't mind it; it's discord

**Comment by NathanKell** [comment]
These contracts (and this program) is getting replaced by a Commercial Applications program, which should hopefully clarify things.

It's worth pointing out that yes, indeed, this program is about creating a comms network _for terrestrial use_, not in the stock-KSP sense, so anything that encourages the player to think in stock-KSP-style-comm-network terms is most certainly a trap.

**Comment by NathanKell** [comment]
The change re: orbital altitude is useful however (it's worth just saying it's a MEO constellation, rather than a specific number, IMO) and we'll bear that in mind for the rework. Thanks!

**Pull request closed without merging**
