### PR TITLE
Earth Station Program Additions

### PR DESCRIPTION
**Pull request by Teykn**
Stations are heavily underdeveloped in RP-1 right now. Here's some additions that I've come up with.

What is added in this PR as of 8/28/23
- Commits contributed by Pap and Zephyr to the StationScience Branch
- New Experiments that apply to crew and science related Station parts in the first three station nodes (`spaceStationPrototypes`, `spaceStationDev`, `earlySpaceStations`)
- "Long Duration Space Habitation" experiment acts as both an abstraction of human health experiments for MOL and Salyuts 1-5, and double acts as an open-ended Duration tracker across all scenes. Consumes 1000 Units/1 Ton of Research Payload every 30 days. This will definitely need to be adjusted.
- Rest of the Experiments included are based on the MOL Proposal Document (Sections 18 and 20). These include:
  - Ocean Surveillance
  - Ultraviolet Radiation Orthicon
  - Airglow Horizon Spectroscopy
  - Narrow Beam Radio Communication
  - Narrow Beam Laser Communication
  - Vapor Distillation Water Purification
  - Solar X-Ray Detection
- Contract Changes: 
  - Added First Space Station Direct, a MOL style contract
  - Added Early Space Station, a 4-times repeatable contract that serves to complete the 180d experiment. After each completion, the requirements get progressively more difficult. This is not MOL compatible though, as it requires docking. (Should this be changed/MOL style contract be added?)
    - Requirements for each completion are listed below. They definitely will be changed.
      - 2 Crew Stay for 30d, requires positive power production
      - 2 Crew Stay for 30d, requires 100W / 100EC/s power production
      - 3 Crew Stay for 30d, requires 250W / 250EC/s power production
      - 3 Crew Stay for 60d, requires 500W / 500EC/s power production 
  - Above contracts and First Space Station modified in order to utilize Long Duration Space Habitation experiment instead of Duration Parameter
  - Disabled Improved Space Station. Will change it later
  
TO DO:
- Find sources or balance the experiments (Currently all of their science and transmission requirements, and some of the cost, mass, and EC requirements are all placeholder)
- Improve the text
- Modify Improved Space Station to emulate Salyut 6/7 and Skylab requirements. This will include a 1 or 2 year experiment that must be completed which completes the program
- Add Skylab and Salyut experiments (Sources on Salyut experiments ESPECIALLY would be much appreciated)

### CODE REVIEW

**Comment by NathanKell** [comment]
Great start!!

Quick hits since busy day.
* I would suggest not directly using power production or "has power at" requirements. Instead use crew duration and experiment completion as requirements, and tune experiment wattage to taste.
* I'd remove the docking requirement and just require more experiments (that aren't on kit in Prototype space stations) - so if you really want to monoblock launch 4 stations you can. But it should be obviously more expensive to do so.

The new RP0CollectScience parameter will be super useful throughout, I'm sure!

**Comment by Teykn** [comment]
Added some more experiments. In total there are 9 experiments for stationPrototypes and 13 experiments for earlySpaceStations.
Here's a [spreadsheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vSVsnjWfgkrqtyEKagEPAn5P1M_NOqHwU8hHcd__RXMUt5LM_lo1muEmarlm3XgCmasyD4IOBcSDU7q/pubhtml) for the current values for the experiments. Recommendations for changes would be nice.

Still thinking about how to handle progressive EC requirements in contracts. Thinking between creating some generic "add-on" experiments and/or modifying the experiments with placeholder values for Early Space Station contracts. For the Improved Space Station contract, there isn't a real need for progressive EC requirements imo, but the EC requirement probably should be increased.

**Comment by SierraHotel84** [comment]
- Modify Improved Space Station to emulate Salyut 6/7 and Skylab requirements. This will include a 1 or 2 year experiment that must be completed which completes the program
- Add Skylab and Salyut experiments (Sources on Salyut experiments ESPECIALLY would be much appreciated)

I think a 1-2 year experiment for an improved station is probably too long.  Skylab only had 3 crews for about 6 months total, and while Salyut stations were used longer, they still weren't continuously manned.  So maybe something like a 6 or 9 month experiment for improved stations, and move anything over a year to modular/modern/advanced stations or whatever we want to call it for Mir/ISS analogs. 

I don't know that the contracts necessarily need progressive EC requirements if the experiments to be completed already need a certain amount.  So for example if you have 13 experiments available for early Space Stations, say each contract/crew rotation requires completing at least 3 (just pulling out a number for discussion sake), then you already have a minimum EC requirement for the station based on the available experiments.

**Comment by Teykn** [comment]
> I think a 1-2 year experiment for an improved station is probably too long. Skylab only had 3 crews for about 6 months total, and while Salyut stations were used longer, they still weren't continuously manned. So maybe something like a 6 or 9 month experiment for improved stations, and move anything over a year to modular/modern/advanced stations or whatever we want to call it for Mir/ISS analogs.

Talked with NK about this in the [discord] (https://discord.com/channels/319857228905447436/620690446540341261/1145974140508061707) actually. He seems to be fine with it since Salyuts 6 and 7 each were crewed for ~2 years (according to wikipedia)

> I don't know that the contracts necessarily need progressive EC requirements if the experiments to be completed already need a certain amount. So for example if you have 13 experiments available for early Space Stations, say each contract/crew rotation requires completing at least 3 (just pulling out a number for discussion sake), then you already have a minimum EC requirement for the station based on the available experiments.

Progressive EC requirements is smth NK wants for the Early Space Station contracts to provide some flexibility in design (e.g launching multiple stations or just launching one). I am currently doing this with the Long Dur. Space Hab. experiments but am still thinking of whether i want to modify historical experiments with (currently) unknown power consumption to add progression, or just add generic add-on experiments for this purpose.

**Comment by NathanKell** [comment]
Progressive EC requirements I think ought to be handled by experiments (or life support or whatever) rather than anything explicit, yeah. I don't think that much progression is needed, but since we're presumably modeling everything from planned early-60s experiments through MOL through early Salyut and Skylab to late Salyut, there's presumably going to be huge variation in power available, and thus power consumed (since no scientist or engineer ever said "that's too much power available, I'm not going to use it" :D ).

As I understand it, since the completion requirement for the experiments that track duration are just experiment-completion, there's no continuous-occupation requirement _per station_, just that there needs to be that much cumulative flight time.

And per discord (but echoing here) I think it's fine for us to conceptualize things as "the US completed the Crewed Lunar program but only partially did early stations, and the Soviets completed Early Stations but only partially completed Crewed Lunar) -- counting the almost-manned Zond program, and N1/L3 design and prototyping, as a similar partial-completion. (As you can see from discord I too started from "that's too long, what about Skylab" but was convinced by Data :D )

**Comment by SierraHotel84** [comment]
I did some more reading as well after those messages and it makes a little more sense now to include longer programs.  

I do like the idea of having some experiments that can just be started and left for cumulative flight time, and some that require crew.

**Comment by SierraHotel84** [comment]
I used the original stations program as a learning opportunity to figure the programs/contracts mechanics and was finally able to get the contracts working correctly.  Going to try adding in some of these experiments and the research payload to see if I can help narrow down some workable values for them.

**Comment by Teykn** [comment]
> I used the original stations program as a learning opportunity to figure out the programs/contracts mechanics and was finally able to get the contracts working correctly. Going to try adding in some of these experiments and the research payload to see if I can help narrow down some workable values for them.

Made a commit so that the PR can be tested in game. Feel free to download the changes. Would recommend downloading some mods with station parts like FASA (only need the Gemini2 parts folder), SSPXR, and RN's Salyut & Skylab to get a better feeling for the experiments, since the express install only comes with station parts from SXT.

**Comment by SierraHotel84** [comment]
Some things I've come across as I've played around with the files.  I'm using just the base Express Install for now just to see how it works with the stock install parts.

-Definitely need to tweak the EC requirements.  For example, a single ISS solar panel, at 1.0 scale and tech 6, produces around 15kW of power, or 15 EC/s.  Long Duration Space Habitation 2 requires 2,000 EC/s, or basically a nuclear reactor, so off by at least an order of magnitude on the Early Station power requirements.  Long Duration 1 is at 100, was it supposed to be 200 for LD2?  Maybe change it to 2,000/min, which would still be 33 EC/s, but seems a little more reasonable. 

-Can't figure out where the difference is, but Long Duration 1 shows up blank in the science archive while all of the other experiments display correctly

long duration 1
long duration 2


-There is a ScienceLabs.cfg file in the main RP-1 science folder that pertains to the mobile processing lab and a couple of others.  With it and the Station Experiments config both enabled, the lab gets 2 Configure Crew Science buttons on the configuration screen, one for the original experiments and one for the new station ones. Disabling this file fixes it, not sure if there is any impact on other parts considered a lab?

mobile lab


-Neither Skylab particularly like the new experiments at all.  Tested the Express Install SXT one as well as the RN Skylab, both show the same thing, the Configure Crew Science button is gone and all of the new experiments are listed fully instead of the allotted number of slots.  

skylab experiments

**Comment by Teykn** [comment]
> -Definitely need to tweak the EC requirements. For example, a single ISS solar panel, at 1.0 scale and tech 6, produces around 15kW of power, or 15 EC/s. Long Duration Space Habitation 2 requires 2,000 EC/s, or basically a nuclear reactor, so off by at least an order of magnitude on the Early Station power requirements. Long Duration 1 is at 100, was it supposed to be 200 for LD2? Maybe change it to 2,000/min, which would still be 33 EC/s, but seems a little more reasonable.
Mentioned on discord but I mixed up units and thought 1 EC/s = 1W, not 1kW. Will definitely be made more reasonable. 

> -Can't figure out where the difference is, but Long Duration 1 shows up blank in the science archive while all of the other experiments display correctly
Huh. I'll have to look into that, I'm not sure why that's the case.
> -There is a ScienceLabs.cfg file in the main RP-1 science folder that pertains to the mobile processing lab and a couple of others. With it and the Station Experiments config both enabled, the lab gets 2 Configure Crew Science buttons on the configuration screen, one for the original experiments and one for the new station ones. Disabling this file fixes it, not sure if there is any impact on other parts considered a lab?
Considering that labs have little use in RP-1, I think it should be fine to remove the part that adds those experiments to parts with labs. 
> -Neither Skylab particularly like the new experiments at all. Tested the Express Install SXT one, and went ahead and installed the RN Skylab, both show the same thing, the Configure Crew Science button is gone and all of the new experiments are listed fully instead of the allotted number of slots. Tried to narrow this one down but it's beyond my feeble searching/coding abilities at this point.
My understanding is that if the number of open slots available exceeds the number of experiments, all experiments are added and can't be configured. There may be other issues though, and I'll have to look into it

Testing it in KSP, I also noticed that on my end the experiments for prototype and dev stations don't show up on the GUI when configured. Also noticed that the configure experiments GUI doesn't list the description, power requirements, or other elements while experiments for the crew capsules do show up. Did you notice any of this?

**Comment by SierraHotel84** [comment]
> Testing it in KSP, I also noticed that on my end the experiments for prototype and dev stations don't show up on the GUI when configured. Also noticed that the configure experiments GUI doesn't list the description, power requirements, or other elements while experiments for the crew capsules do show up. Did you notice any of this?

I did, and that's actually what led me to looking in the Science Archive and noticing LDSH1 not showing up and got distracted by that instead.  Forgot to mention it.  I kind of went down a few rabbit holes when I was poking around in different files.

Agreed on the lab part, though it does make me wonder if using the lab function may fix the Skylabs.  I'll play around with that some more.

**Comment by Teykn** [comment]
All of the MOL/Early Salyut experiments have been fixed. They should now function in-game. I have not adjusted the values though. I'll do that at a later time.

Another change is that those early experiments apply to both stations in the `spaceStationPrototypes` and `spaceStationDev`. Noted that the experiments broke if I tried using an OR for both tiers, so I had to combine them into one. I probably won't look for Salyut exclusive experiments because of this, or if I do, prototype stations will get access to them as well.

**Comment by SierraHotel84** [comment]
>  I probably won't look for Salyut exclusive experiments because of this, or if I do, prototype stations will get access to them as well.

Doesn't seem like a huge deal since the prototype stations are so much more limited, kind of takes care of itself with built-in controls for what can be accomplished.

**Pull request closed without merging**
