### PR TITLE
added Russian translation

### PR DESCRIPTION
**Pull request by Tagir-1**
Russian localization. For now text from en-us.cfg only

### CODE REVIEW

**Comment by NathanKell** [comment]
Awesome! That this exists will give us impetus to pull more hardcoded strings out of the game and make them localizable.

Any chance you can do RO as well? :)

**Comment by Tagir-1** [comment]
I'll try contributing to RO too. I know multiple people who'd like to play RP-1, but the difficulty curve of it is multiplied by language barrier.

**Comment by Pl3aseJust3ndMySuffering** [comment]
#rp0_EngineersReport_Concern_UntooledParts_DescriptionSingle = Присутсвует деталь, производимая без оснастки.
	#rp0_EngineersReport_Concern_UntooledParts_DescriptionMany = Присутсвуют детали, производимые без оснастки (<<1>>) шт.
'Присутсвует' > 'Присутствует'
'Присутсвуют' > 'Присутствуют'
Otherwise a perfect translation. Thanks.

**Comment by NathanKell** [comment]
Gonna merge this, though please note the loc file is changing all the time so this will need updating. :)

**Comment by NathanKell** [comment]
(note I changed 'Unlock Subsidy' to 'Unlock Credit' -- and also note the comment above re: those two translations.)

**Pull request merged**
