### PR TITLE
Interplanetary contract issues

### PR DESCRIPTION
**Pull request by Ballatik**
Based on issue #2288 

- Split Venus landing into Capstone and optional repeatable, added optional to program definition
- Split Mars Landing and Mars Rover into required and optional repeatable, added optionals to program definition
- Split Mercury, Pluto, and Charon Landing into required and optional repeatables, added optionals to program definitions
- Crewed Targeted Moon Landing looks to be intentional.  The program requires 2 completions, and the contract is completable twice.
- Titan Rover was checking for SaturnObservation as the active program, but wasn't listed in the program.  It doesn't make sense there, so changing the check and optional listing to be SaturnMoonLandings.

### CODE REVIEW

**Comment by NathanKell** [comment]
Thanks!

* Looks like there's an issue with the change to the Programs.cfg file? There's an awful lot of changes that seem unrelated to what you mention changing. Did you maybe use the web editor and paste some changes in, or something?
* I'm a bit concerned with unlimited repeats on the Venus Landing optional contract, because Venus landings are pretty easy and Venus windows are common. But I think we can try unlimited for now.

**Comment by siimav** [comment]
> I'm a bit concerned with unlimited repeats on the Venus Landing optional contract, because Venus landings are pretty easy and Venus windows are common. But I think we can try unlimited for now.

Yeah, since the player is most likely already taking the Science Orbit repeatable then adding a landing on top of that is almost free. Maybe have just a small reward on this?

**Comment by Ballatik** [comment]
> Did you maybe use the web editor and paste some changes in, or something?

Possibly yes, or possibly just my editor setup with line breaks.  I'll figure that out and fix it.

> Yeah, since the player is most likely already taking the Science Orbit repeatable then adding a landing on top of that is almost free. Maybe have just a small reward on this?

I was going on the idea that with an 8 year program you're likely only getting 4 windows meaning the required plus 3 repeats if all goes well.  I hadn't thought about piggybacking though, and really once you have a craft that works repeating the mission is extremely easy.  

Long term, I think these repeats should have increasing requirements, but that's a bigger change.  For now I think reducing the rewards for one or both is a good idea, or even giving diminishing rewards for each repeat.

**Comment by Ballatik** [comment]
> There's an awful lot of changes that seem unrelated to what you mention changing.

Atom was stripping extraneous whitespace.  I found and killed that setting so the diff is much more readable.

Also lowered rewards on Venus repeatables.

**Pull request merged**
